name: Coverage

on: [push]

jobs:
  build:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate coverage
        run: coverage run --source=src -m pytest tests/unit
      - name: Report coverage
        run: coverage report --fail-under=100

