name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.11"
    steps:
    - uses: actions/checkout@v3
    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-mock
    - name: Run unit tests
      run: pytest tests/unit

